### ISSUE TITLE
bug: PR auto-test runs on changes from target branch

### ISSUE THREAD

**Issue by WillDaSilva** [meltano/hub#963] opened 2022-10-25 16:39 UTC
Context: https://github.com/meltano/hub/pull/961#issuecomment-1290845199

**Comment by WillDaSilva** [comment] 2022-10-25 18:34
It seems to have happened here too:
- db2: https://github.com/meltano/hub/pull/964#issuecomment-1290964895
- Postgres: https://github.com/meltano/hub/pull/964#issuecomment-1290966187

**Comment by WillDaSilva** [comment] 2022-10-25 19:17
I'm pretty stumped by this right now. Given the low impact I'm going to deprioritize this for now. @pnadolny13 Let me know if this becomes a greater issue.

**Comment by WillDaSilva** [comment] 2022-11-14 15:36
@pnadolny13 Have you noticed this problem since #971 was merged? I think that PR might've fixed this issue too.

**Comment by pnadolny13** [comment] 2022-11-21 17:03
@WillDaSilva I havent noticed it recently so yeah that probably fixed it. We can close this for now and re-open if we notice it pop back up again.

**Comment by pnadolny13** [comment] 2022-11-28 21:41
@WillDaSilva I'm not sure if this is the same cause but I saw it again on https://github.com/meltano/hub/pull/1047#issuecomment-1329391160. tap-spotify wasnt changed in my PR but it got tested anyways, the others were correct. I re-opened this issue but feel free to close and open another if this isnt the right spot for its.

**Comment by aaronsteers** [comment] 2022-11-30 03:26
Looks like there was an edit 2 days ago on `tap-spotify--matatika` here: 

https://github.com/meltano/hub/commits/main/_data/meltano/extractors/tap-spotify/matatika.yml

This likely caused the diff between the the feature branch for #1047 and `main`.

**Comment by pnadolny13** [comment] 2022-11-30 15:00
@aaronsteers ahh ok so if I understand correctly thats expected behavior because my PR branch was out of sync? If so we can re-close this 😅

**Comment by aaronsteers** [comment] 2022-11-30 15:44
Yeah - I think that's it. The diff against main seems to work properly, just that 'from us' or 'from them' isn't distinguished. We could additionally try to pass this through a  'changed by us' filter, but I think for now, we're probably okay to keep deprioritized.

**Closed** 2022-11-30 21:44 UTC
Labels: kind/Bug
