### ISSUE TITLE
Sort Hub search results by number of projects using the plugin

### ISSUE THREAD

**Issue by aaronsteers** [meltano/hub#1144] opened 2023-01-31 18:35 UTC
As a way to naturally give proper prioritization of widely used and successful plugins on the Hub, we can sort search results output based on the "Projects (last 3 months)" count for each.

At least in most cases, this sort would naturally bring the best result to the top of the results - without having to build a complex algorithm.

Since taps and targets almost always have more results than utilities, files, and transformers, this would almost certainly solve this one as well:

- https://github.com/meltano/hub/issues/1057

**Comment by tayloramurphy** [comment] 2023-02-01 16:10
Search is hard - I worry if we weight it too much by output then legitimate matches would be pushed down too far. Hard to know w/o digging in deeper though. (I spent too much time in a past life fine tuning elasticsearch with customized tokens and stems 🤪 )

**Comment by tayloramurphy** [comment] 2023-02-02 16:57
Duplicate of https://github.com/meltano/hub/issues/862

**Closed by tayloramurphy** 2023-02-02 16:57 UTC
