### ISSUE TITLE
🐛 BUG: very slow load time (10mins) from RSA 🇿🇦

### ISSUE THREAD

**Issue by kgpayne** [meltano/hub#1069] opened 2022-12-06 18:32 UTC
**Note:** This issue template is for issues related to the MeltanoHub or plugin definitions. 
If you're having a problem with a tap or target, please open an issue on that repository so the maintainers can address it.

**Describe the bug**
Loading hub.meltano.com with a clear browser cache takes 10.1 minutes from South Africa.

**Expected behavior**
Ideally CDN coverage would support faster load times than that. Other regions experience millisecond load times.

**Screenshots**

<img width="1439" alt="Screenshot 2022-12-06 at 20 23 04" src="https://user-images.githubusercontent.com/5585874/205992724-1c6288e6-94c0-4563-9dce-3eda342a0d9a.png">

<img width="414" alt="Screenshot 2022-12-06 at 20 26 17" src="https://user-images.githubusercontent.com/5585874/205992817-0b9ff381-90d3-43dc-a21d-ff3261e4b54b.png">

**Desktop (please complete the following information if applicable):**
 - OS: [e.g. iOS] MacOS Version 12.6
 - Browser [e.g. chrome, safari] Chrome Version 107.0.5304.121 (Official Build) (x86_64)

**Comment by tayloramurphy** [comment] 2022-12-06 20:25
@kgpayne holy crap! That's awful. Is there something we can adjust in Netlify to help with this @aaronsteers ?

I'm unassigning Pat b/c I don't think there's anything he or I can do to help 😬

**Comment by aaronsteers** [comment] 2022-12-07 05:47
@kgpayne - I can't infer much from the above screenshots in terms of root cause. I think it's important to distinguish time to 'fully load' the page/site, versus time to get responsiveness.

Gridsome is designed to progressively download first low-res images and then gradually higher and higher resolution images. We have not put any checks or limits on the logo sizes, but it could be worth reviewing the largest logos and downgrading quality for any that are outside an acceptable size limit.

**Comment by cjohnhanson** [comment] 2022-12-16 22:59
> It seems much better today (with browser cache disabled), so maybe I have triggered a CDN POP cache somewhere local to me

My guess would be something like this. 
I poked around in Netlify a bit, we can get location page view data if we upgraded our plan but I didn't immediately see any configuration options that could help out here. 

+1 to closing as a transient bug.

**Closed** 2022-12-17 06:10 UTC
Labels: kind/Bug, valuestream/Hub
