### ISSUE TITLE
Introduce `ref` and/or `plugin_id`, as functional replacement to `variant`

### ISSUE THREAD

**Issue by aaronsteers** [meltano/hub#546] opened 2022-06-04 05:12 UTC
@edgarrmondragon and I were discussing this last week and it seems worth logging for discussion/planning.

Currently we have `variant` as differentiator between various `plugin_name` values that otherwise would collide with each other.

I think there's a way we could do this in a backwards compatible manner.

## Proposal

1. we can keep `variant` as a key
1. `plugin_id` is new and optional, calculated as `{plugin}--{variant}` if not otherwise provided
1. with `plugin_id` becoming the primary identifier, `variant` is no longer required if `plugin_id` is specified.
1. we can add `ref` in two forms: `lockfile_ref` and `remote_ref`
   1. `lockfile_ref` would default to something like `./plugins/{plugin_type}/{plugin_id}.lock`
   1. `remote_ref` would default to something like `https://hub.meltano.com/meltano/api/v1/plugins/{plugin_type)/{plugin_id}.lock`

**Comment by tayloramurphy** [comment] 2023-01-23 21:57
Duplicate of https://github.com/meltano/meltano/issues/7058

**Closed by tayloramurphy** 2023-01-23 21:57 UTC
