### ISSUE TITLE
bug: description starts of the same regardless of plugin type

### ISSUE THREAD

**Issue by sbalnojan** [meltano/hub#885] opened 2022-10-10 08:13 UTC
https://hub.meltano.com/loaders/target-postgres/

<img width="916" alt="image" src="https://user-images.githubusercontent.com/43072233/194823318-8c376315-4753-475e-bee1-88b15652c10f.png">

At the top of every description it says "the ... pull data.... ". That line only works for extractors, not loaders or transformers. It currently is generic to all plugin types.

**Comment by pnadolny13** [comment] 2022-10-10 14:41
@sbalnojan this looks like a duplicate of https://github.com/meltano/hub/issues/885. Theres discussion in the other one for getting it assigned/prioritized.

Can you close it out if it is?

**Comment by tayloramurphy** [comment] 2022-10-10 16:52
Duplicate of https://github.com/meltano/hub/issues/864

**Closed by tayloramurphy** 2022-10-10 16:52 UTC
