### ISSUE TITLE
429 Response Codes

### ISSUE THREAD

**Issue by visch** [meltano/hub#599] opened 2022-06-14 02:46 UTC
To replicate

1. Go to https://hub.meltano.com
1. Click Extractors
1. Click an Extractor
1. Click the MeltanoHub icon on the top left of the page

Do steps 2-3 quickly

Here's a video of this happening

https://user-images.githubusercontent.com/8680264/173482873-a61af4d0-c427-4411-9e8c-82003b30a17b.mp4

--

Wild guess

Something to do with all the requests for Images and no cache control on this images?

**Comment by tayloramurphy** [comment] 2022-06-14 16:08
Ha! Yeah - can confirm I get the same thing. Likely a limitation on Netlify's end. We have https://github.com/meltano/internal-general/issues/247 which is an internal issue about moving hosting to Cloudflare. 

I'm not sure there's much we can do here. @aaronsteers any ideas?

**Comment by pnadolny13** [comment] 2022-06-21 17:54
@tayloramurphy @alexmarple I also ran into this today and got some weird buggy side affects. Is there any short term fixes we can do on our side to cache those images or potentially load only a subset? It shows up for me almost immediately so the browsing experience is fairly interrupted.

**Comment by alexmarple** [comment] 2022-06-21 19:37
@pnadolny13 oh that's fun. we could try a plugin like: https://github.com/wildlyinaccurate/jekyll-responsive-image with cacheing set to true. this might definitely be an issue with netlify but i feel like they wouldn't do us dirty like that.

**Comment by pnadolny13** [comment] 2022-06-21 20:30
@tayloramurphy I'd consider this a relatively high urgency bug, its a struggle to use the hub in its current state. If I dont land on what im looking for quickly then I start to get lots of 429's so I have to stop for a minute and let it cool down 😄 . Do we think Cloudflare will happen soon and do we know if it would resolve this issue?

@alexmarple is that something thats easy to test out? I'd assume that making the change PR then testing on the preview app would give us a good sense of whether it helps while still using Netlify or not.

**Comment by pandemicsyn** [comment] 2022-06-22 15:52
@alexmarple and @pandemicsyn - What likely root causes would drive this and what mitigations would be helpful? Could this be related to the new omnipresent search box backend needing to loading all images on all pages?

429 means netlify is rate limiting the user , so caching would definitely help. Just loading `https://hub.meltano.com/extractors/` results in **355** (🤯 ) requests! Thats gonna be really iffy experience for users with slower connections.

**Comment by visch** [comment] 2022-06-22 16:11
Cache-Control headers have to go somewhere, webserver is going to do it wherever that's at.

For a quick fix a Netlifiy setting as I'd assume they are running the web server (nginx/apache) serving your content 🤷  should be pretty much *.png *.jpg etc and cache control them to a day or something, then make a seperate issue to do this more accurately

**Comment by tayloramurphy** [comment] 2022-06-22 16:14
@pnadolny13 with regard to cloudflare, https://github.com/meltano/internal-general/issues/247 is the issue and it's scheduled for end of June / early July (cc @aaronsteers)

I'm open to any short term fixes to make the experience a bit better but I don't have a good sense of the optimal solution. Looking to @pandemicsyn @alexmarple @aaronsteers on that!

**Comment by pandemicsyn** [comment] 2022-06-22 18:46
> Just loading https://hub.meltano.com/extractors/ results in 355 (🤯 ) requests! Thats gonna be really iffy experience for users with slower connections.

> Worth mentioning that with this pattern and volume of requests CloudFlare would also probably start throwing up barriers.

@tayloramurphy ☝️ cloudflare isn't a fix for this. Adding some cache control is the "temp" fix. Easiest way to fix up the cache control headers is probably just by editing the netlify.toml or using a _headers file for the hub. Not sure how we ended up deploying the hub but one of those two should work I think: https://docs.netlify.com/routing/headers/#custom-headers

Long term we're still gonna need to implement some of sort lazy loading or pagination pattern because on an empty cache,  fetching 100's of extractor images is gonna be a really iffy experience in a lot of parts of the world, and I assume its only gonna get worst as we add more extractors. 

The google pagespeed tests actually refer to our network load as "enormous" which is sorta amusing: 😁 

<img width="537" alt="Screen Shot 2022-06-22 at 1 39 43 PM" src="https://user-images.githubusercontent.com/333354/175113028-5bc1f673-9a2f-4efc-82e3-57bbff6e0f2b.png">

**Comment by tayloramurphy** [comment] 2022-06-22 22:16
@pandemicsyn appreciate the context and info! 

I'm ok to merge the band-aid if it helps. I think this is something we'll have to take into account @alexmarple on the redesign.

**Comment by tayloramurphy** [comment] 2022-06-22 22:16
@aaronsteers assigning to you as it's not clear who best to fix it or if https://github.com/meltano/hub/pull/619 is indeed the band-aid we want to apply right now.

**Comment by aaronsteers** [comment] 2022-06-24 17:18
Was closed automatically by #619 but I'm reopening while we confirm the fix.

@tayloramurphy, @pnadolny13, @visch, feel free to close (again 😅) once fix is confirmed.

**Comment by tayloramurphy** [comment] 2022-06-24 21:57
@aaronsteers I tested in my regular window and in a private window and I wasn't able to reproduce the 429's. It did get a little slow in the private window but it still worked. I'm ok to close and folks can reopen if it's still a problem.

**Closed by tayloramurphy** 2022-06-24 21:57 UTC
Labels: kind/Bug
